name: Build and test.

on:
  workflow_dispatch:
  pull_request:
    branches:
      - development
    paths:
      - 'src/**'
      - '.github/workflows/development-pr-ci.yml'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build and test with Maven
        run: ./mvnw -B verify --file pom.xml
